In [2]:
# Import NumPy
import numpy as np

In [7]:
# Matrix-Matrix Multiplication Function
def matrixMult(U, V):
    assert U.shape[1] == V.shape[0]
    result = np.zeros([U.shape[0], V.shape[1]])
    for i in range(U.shape[0]):
        for j in range(V.shape[1]):
            result[i,j] = sum(U[i,:] * V[:,j])
    return result

In [18]:
# Example 1
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

matrixMult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [20]:
# Check result with Numpy's dot function
np.dot(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
# Check result with Numpy's @ operator
U @ V

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [22]:
# Check result with Numpy's matmul function
np.matmul(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])